#!/usr/bin/python

# This is a part of the external applet Calendar for Cairo-Dock
# Based on demo_bash
#
# Copyright : (C) 2010-2011 by Nochka85, Fabounet and matttbe
# E-mail : fabounet@glx-dock.org
#
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# http://www.gnu.org/licenses/licenses.html#GPL

from CDBashApplet import CDBashApplet

if __name__ == '__main__':
	CDBashApplet().run()
